# Centralized constants for CarbonTwin AI calculations and simulations

# --- Ground & Air Transportation ---
VEHICLE_FACTORS = {
    "gasoline": 0.192,
    "diesel": 0.232,
    "hybrid": 0.109,
    "electric": 0.053,
    "none": 0.0
}
TRANSIT_FACTOR = 0.04  # kg CO2e per km
MILES_TO_KM = 1.60934
FLIGHT_EMISSIONS_FACTOR = 0.15  # kg CO2e per passenger-km

# --- Home Energy ---
INR_TO_KWH_DIVISOR = 8.0
SOLAR_DAILY_GEN_HOURS = 4.0
DAYS_IN_MONTH = 30.0
MONTHS_IN_YEAR = 12
GRID_EMISSIONS_FACTOR_KG_PER_KWH = 0.4
SOLAR_CAPACITIES = {
    "none": 0.0,
    "small": 2.0,
    "medium": 5.0,
    "large": 10.0
}

# --- Food Habits ---
FOOD_CATEGORY_FACTORS = {
    "beef": 0.060,
    "dairy": 0.021,
    "poultry": 0.006,
    "fish": 0.005,
    "grains": 0.0015,
    "vegetables": 0.001,
    "plant_protein": 0.002,
    "other": 0.003
}
FALLBACK_DAILY_FOOD_EMISSIONS = 2500.0
DAYS_IN_YEAR = 365.0

# --- Shopping & Consumption ---
CLOTHING_FACTORS = {
    "shirts": 8.0,
    "pants": 15.0,
    "outerwear": 30.0,
    "shoes": 20.0
}
ELECTRONICS_FACTORS = {
    "phones": 60.0,
    "laptops": 250.0,
    "tvs": 350.0,
    "accessories": 10.0
}
FOOD_DELIVERY_EMISSIONS = 1.5
PACKAGE_DELIVERY_EMISSIONS = 2.2
LARGE_PURCHASE_FACTORS = {
    "furniture": 300.0,
    "appliances": 500.0,
    "ev_vehicle": 6000.0,
    "gas_vehicle": 12000.0,
    "other": 150.0
}
LARGE_PURCHASE_COST_MULTIPLIER = 0.1

# --- Scoring System ---
SCORE_THRESHOLD_EXCELLENT_TONS = 2.0
SCORE_THRESHOLD_POOR_TONS = 20.0

# --- Digital Twin Rules & Multipliers ---
BICYCLE_SWITCH_THRESHOLD_KM = 100.0
BICYCLE_SAVINGS_PER_KM = 0.15
TRANSIT_SAVINGS_PER_KM = 0.10
FLIGHT_SAVINGS_PER_FLIGHT = 300.0
ELECTRICITY_BILL_REDUCTION_FACTOR = 0.8
INR_TO_USD_CONVERSION_FACTOR = 80.0
ANNUAL_SOLAR_SAVINGS_USD = 150.0
DIET_REDUCTION_FACTOR = 0.5
DIET_REDUCTION_SAVINGS_USD = 200.0
DIET_HIGH_MEAT_SHIFT_SAVINGS_USD = 150.0
DIET_MIXED_SHIFT_SAVINGS_USD = 250.0
FOOD_DELIVERY_REDUCTION_COUNT = 2
FOOD_DELIVERY_FEE_SAVINGS_USD = 5.0
PACKAGE_DELIVERY_REDUCTION_COUNT = 1
PACKAGE_DELIVERY_FEE_SAVINGS_USD = 10.0
CLOTHING_REDUCTION_FACTOR = 0.85
CLOTHING_ITEM_COSTS = {
    "shirts": 30.0,
    "pants": 50.0,
    "outerwear": 100.0,
    "shoes": 80.0
}
CLOTHING_SPEND_REDUCTION_RATE = 0.15

# --- Digital Twin Classification / Archetype Thresholds ---
FREQUENT_FLYER_FLIGHTS = 3
FREQUENT_FLYER_EMISSIONS_KG = 2000.0
HIGH_CONSUMER_SHOPPING_KG = 1500.0
HIGH_CONSUMER_DELIVERIES = 6
HIGH_CONSUMER_CLOTHING_ITEMS = 5
URBAN_OPTIMIZER_RATIO = 0.6
ENERGY_EFFICIENT_ENERGY_KG = 500.0
ENERGY_EFFICIENT_RENEWABLE_PCT = 40.0

# --- Simulator Levers & Projections ---
SOLAR_INSTALLATION_COST_USD = 2500.0
APPLIANCE_OPTIMIZATION_COST_USD = 500.0
BIKE_PURCHASE_COST_USD = 300.0
DRIVING_SAVINGS_PER_KM = 0.15
METRO_SAVINGS_PER_KM = 0.10
CARPOOL_SAVINGS_PER_KM = 0.075
REDUCED_FLIGHT_SAVINGS_USD = 250.0
SOLAR_SAVINGS_PER_KWH = 0.15
SOLAR_UPGRADE_GEN_DIFF_KWH = 360.0
APPLIANCE_OPTIMIZATION_USAGE_FACTOR = 0.8
APPLIANCE_OPTIMIZATION_SAVINGS_RATE = 0.15
REDUCE_ELECTRICITY_SAVINGS_RATE = 0.15
REDUCE_BEEF_SAVINGS_PER_G = 0.015
DIET_TRANSITION_SAVINGS_TABLE = {
    "high_meat": {
        "balanced": 150.0,
        "vegetarian": 400.0,
        "vegan": 750.0
    },
    "mixed": {
        "vegetarian": 250.0,
        "vegan": 600.0
    },
    "vegetarian": {
        "vegan": 350.0
    }
}

COMBINED_DELIVERY_SAVINGS_PER_ORDER = 3.50
ELECTRONICS_ITEM_COSTS = {
    "phones": 800.0,
    "laptops": 1200.0,
    "tvs": 600.0,
    "accessories": 50.0
}
CO2_SAVED_PER_TREE_KG = 20.0

# --- Recommendations Constants ---
METRO_RECOMMENDATION_SAVINGS_PER_KM = 0.05
CARPOOL_RECOMMENDATION_SAVINGS_PER_KM = 0.075
CYCLE_RECOMMENDATION_SAVINGS_PER_KM_CAR = 0.15
CYCLE_RECOMMENDATION_SAVINGS_PER_KM_FALLBACK = 0.05
CYCLE_RECOMMENDATION_FACTOR_FALLBACK = 0.05
MEAT_REDUCTION_RECOMMENDATION_SAVINGS_HIGH_MEAT = 200.0
MEAT_REDUCTION_RECOMMENDATION_SAVINGS_FALLBACK = 300.0
MEAT_REDUCTION_RECOMMENDATION_SAVED_KG = 800.0
ENERGY_EFFICIENCY_RECOMMENDATION_KWH_THRESHOLD = 100.0
ENERGY_EFFICIENCY_REDUCTION_PERCENT = 15.0
ENERGY_EFFICIENCY_ELECTRICITY_COST_USD = 0.15
RENEWABLE_PROVIDER_TARGET_PERCENT = 50.0


